// bless the cute dork god

Class SayaHammer : SWWMWeapon
{
	Default
	{
		Tag "$T_SAYAHAMMER";
		Inventory.PickupMessage "$I_SAYAHAMMER";
		SWWMWeapon.Tooltip "$TT_SAYAHAMMER";
		Inventory.Icon "graphics/HUD/Icons/W_SayaHammer.png";
		Weapon.SlotNumber 8;
		Weapon.SlotPriority 1.;
		Weapon.SelectionOrder 100;
		Weapon.AmmoType1 "SayaKiraMana";
		Weapon.AmmoGive1 120;
		+WEAPON.AMMO_OPTIONAL;
		+WEAPON.MELEEWEAPON;
		+WEAPON.EXPLOSIVE;
		+WEAPON.BFG;
	}
	States
	{
	Spawn:
		XZW1 A -1;
		Stop;
	}
}
